import Head from "next/head";
import Apod from "../components/apod-card/Apod";
import Creds from "../components/apod-card/Cred";
import Header from "../components/header/Header";
import Info from "../components/apod-card/Info";
import Loading from "../components/Loading";
import Paragraph from "../components/apod-card/Paragraph";

export default function Home() {
  return (
    <div className="font-inter selection:bg-neutral-200 bg-neutral-50">
      <Head>
        <title>apod :)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Loading /> */}

      <Header />

      <main className="text-center mb-8 sm:mx-8 sm:my-8 space-y-8 sm:bg-neutral-100 px-8 sm:py-8 rounded-3xl lg:flex lg:items-center lg:text-left lg:space-y-0 lg:space-x-8">
        <div className="flex lg:w-full justify-center">
          <div className="xl:max-w-xl lg:max-w-md space-y-4">
            <Info
              title="Venus and Mars: Passing in the Night"
              date="2022 March 29"
            />
            <div className="hidden lg:block">
              <Paragraph text="Explanation: When two planets pass on the night sky, they can usually be seen near each other for a week or more. In the case of this planetary conjunction, Venus and Mars passed within 4 degrees of each other earlier this month. The featured image was taken a few days prior, when Venus was slowing rising in the pre-dawn sky, night by night, while Mars was slowly setting. The image, a four-part mosaic, was captured in Brazil from the small town Teresópolis. Besides Venus and Mars, the morning sky now also includes the more distant planet Saturn. Of course, these conjunctions are only angular -- Venus, Mars, and Saturn continue to orbit the Sun in very different parts of our Solar System. Next week, the angle between Saturn and Mars will drop to below a quarter of a degree." />
            </div>
            <Creds
              url="https://www.instagram.com/kikofairbairn/"
              credit="Carlos Kiko Fairbairn"
            />
          </div>
        </div>
        <Apod url="/VenusMars_Fairbairn_960_annotated.jpg" />
        <div className="lg:hidden text-left w-full flex justify-center bg-neutral-100 p-8 sm:pt-8 rounded-3xl">
          <div className="max-w-md">
            <Paragraph text="Explanation: When two planets pass on the night sky, they can usually be seen near each other for a week or more. In the case of this planetary conjunction, Venus and Mars passed within 4 degrees of each other earlier this month. The featured image was taken a few days prior, when Venus was slowing rising in the pre-dawn sky, night by night, while Mars was slowly setting. The image, a four-part mosaic, was captured in Brazil from the small town Teresópolis. Besides Venus and Mars, the morning sky now also includes the more distant planet Saturn. Of course, these conjunctions are only angular -- Venus, Mars, and Saturn continue to orbit the Sun in very different parts of our Solar System. Next week, the angle between Saturn and Mars will drop to below a quarter of a degree." />
          </div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
