import Head from "next/head";
import Image from "next/image";
import Loading from "../components/Loading";

export default function Home() {
  return (
    <div className="font-inter">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Loading /> */}

      <main className=""></main>

      <footer className=""></footer>
    </div>
  );
}
